language: ruby
sudo: false

rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.3
  - 2.1.7
  - 2.0.0
  - jruby-9.0.5.0
  - jruby-19mode
  - ruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head

before_install:
  - gem install bundler -v 1.17.3

bundler_args:
  --without test --jobs 3 --retry 3

before_script:
  - bundle update

