language: ruby
sudo: false

rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - ruby-head

before_install:
  - gem update
  - gem install bundler --force

bundler_args: --jobs 3 --retry 3

before_script:
  - bundle update
