env:
  global:
    - COVERAGE=true

language: ruby

rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4

before_install:
  - gem update
  - gem install bundler --force

bundler_args: --jobs 3 --retry 3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - bundle update

script:
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $TRAVIS_TEST_RESULT
